provider: "AWS"
# ConfigFile should be different depending on the provider


# Region where resources should be created
region = "us-east-1"
# Resources will be prefixed with this to avoid clashing names
prefix = "openticate"
# Number of instance to create
number: 5
# AWS Instance Type for aws provider
type = "t2.medium"
